service: aws-serverless-dyndns

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "route53:ChangeResourceRecordSets"
      Resource: "arn:aws:route53:::hostedzone/${file(config.${self:provider.stage}.yml):hostedZoneId}"

functions:
  dnsupdate:
    handler: handler.dnsupdate
    events:
      - http:
          path: dnsupdate
          method: get
    environment:
      apiSecret: ${file(config.${self:provider.stage}.yml):apiSecret}
      hostedZoneId: ${file(config.${self:provider.stage}.yml):hostedZoneId}
      domain: ${file(config.${self:provider.stage}.yml):domain}
